- name: "download influxdb rpm"
  get_url:
  args: 
    url: https://influxdb.s3.amazonaws.com/{{ influxdb_rpm }}
    dest: /tmp/{{ influxdb_rpm }}
    sha256sum: "{{ influxdb_sha256 }}"
    force: no
- name: "ensure influxdb is installed"
  yum: name=/tmp/{{ influxdb_rpm }} state=present
- name: "configure influxdb"
  template: src=influxdb-9.4.2.conf dest=/etc/opt/influxdb/influxdb.conf
  notify:
    - restart influxdb
    - create fluo user
- name: "create data dir"
  file: path={{ default_data_dirs[0] }}/influxdb state=directory owner=influxdb group=influxdb
- name: "ensure influxdb is running (and enable it at boot)"
  service: name=influxdb state=started enabled=yes
  notify:
    - create fluo user
